/*
 * Consumer Data Standards
 * Client Reference Implementation for the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.reference.models;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of constraint described. See the next section for an overview of
 * valid values and their meaning
 */
@JsonAdapter(ConstraintType.Adapter.class)
public enum ConstraintType {

    MAX_BALANCE("MAX_BALANCE"),

    MAX_LIMIT("MAX_LIMIT"),

    MIN_BALANCE("MIN_BALANCE"),

    MIN_LIMIT("MIN_LIMIT"),

    OPENING_BALANCE("OPENING_BALANCE");

    private String value;

    ConstraintType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static ConstraintType fromValue(String text) {
        for (ConstraintType b : ConstraintType.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

    public static class Adapter extends TypeAdapter<ConstraintType> {
        @Override
        public void write(final JsonWriter jsonWriter, final ConstraintType enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public ConstraintType read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return ConstraintType.fromValue(String.valueOf(value));
        }
    }
}
