/*
 * Consumer Data Standards
 * Client Reference Implementation for the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.reference.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * MetaPaginated
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-11T19:35:49.725+10:00")
public class MetaPaginated {
    @SerializedName("totalPages")
    private Integer totalPages = null;

    @SerializedName("totalRecords")
    private Integer totalRecords = null;

    public MetaPaginated totalPages(Integer totalPages) {
        this.totalPages = totalPages;
        return this;
    }

    /**
     * The total number of pages in the full set
     * 
     * @return totalPages
     **/
    @ApiModelProperty(required = true, value = "The total number of pages in the full set")
    public Integer getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    public MetaPaginated totalRecords(Integer totalRecords) {
        this.totalRecords = totalRecords;
        return this;
    }

    /**
     * The total number of records in the full set
     * 
     * @return totalRecords
     **/
    @ApiModelProperty(required = true, value = "The total number of records in the full set")
    public Integer getTotalRecords() {
        return totalRecords;
    }

    public void setTotalRecords(Integer totalRecords) {
        this.totalRecords = totalRecords;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetaPaginated metaPaginated = (MetaPaginated) o;
        return Objects.equals(this.totalPages, metaPaginated.totalPages)
                && Objects.equals(this.totalRecords, metaPaginated.totalRecords);
    }

    @Override
    public int hashCode() {
        return Objects.hash(totalPages, totalRecords);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetaPaginated {\n");

        sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
        sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
