/*
 * Consumer Data Standards
 * Client Reference Implementation for the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.reference.models;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of fee
 */
@JsonAdapter(FeeType.Adapter.class)
public enum FeeType {

    DEPOSIT("DEPOSIT"),

    EVENT("EVENT"),

    EXIT("EXIT"),

    PAYMENT("PAYMENT"),

    PERIODIC("PERIODIC"),

    PURCHASE("PURCHASE"),

    TRANSACTION("TRANSACTION"),

    UPFRONT("UPFRONT"),

    WITHDRAWAL("WITHDRAWAL");

    private String value;

    FeeType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static FeeType fromValue(String text) {
        for (FeeType b : FeeType.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

    public static class Adapter extends TypeAdapter<FeeType> {
        @Override
        public void write(final JsonWriter jsonWriter, final FeeType enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public FeeType read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return FeeType.fromValue(String.valueOf(value));
        }
    }
}
