/*
 * Consumer Data Standards
 * Client Reference Implementation for the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.reference.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import au.org.consumerdatastandards.reference.models.BankingProductDetail;
import au.org.consumerdatastandards.reference.models.Links;
import au.org.consumerdatastandards.reference.models.Meta;
import io.swagger.annotations.ApiModelProperty;

/**
 * ResponseBankingProductById
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-11T19:35:49.725+10:00")
public class ResponseBankingProductById {
    @SerializedName("data")
    private BankingProductDetail data = null;

    @SerializedName("links")
    private Links links = null;

    @SerializedName("meta")
    private Meta meta = null;

    public ResponseBankingProductById data(BankingProductDetail data) {
        this.data = data;
        return this;
    }

    /**
     * Get data
     * 
     * @return data
     **/
    @ApiModelProperty(required = true, value = "")
    public BankingProductDetail getData() {
        return data;
    }

    public void setData(BankingProductDetail data) {
        this.data = data;
    }

    public ResponseBankingProductById links(Links links) {
        this.links = links;
        return this;
    }

    /**
     * Get links
     * 
     * @return links
     **/
    @ApiModelProperty(required = true, value = "")
    public Links getLinks() {
        return links;
    }

    public void setLinks(Links links) {
        this.links = links;
    }

    public ResponseBankingProductById meta(Meta meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Get meta
     * 
     * @return meta
     **/
    @ApiModelProperty(required = true, value = "")
    public Meta getMeta() {
        return meta;
    }

    public void setMeta(Meta meta) {
        this.meta = meta;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseBankingProductById responseBankingProductById = (ResponseBankingProductById) o;
        return Objects.equals(this.data, responseBankingProductById.data)
                && Objects.equals(this.links, responseBankingProductById.links)
                && Objects.equals(this.meta, responseBankingProductById.meta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, links, meta);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseBankingProductById {\n");

        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    links: ").append(toIndentedString(links)).append("\n");
        sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
